"""Initial schema (arch §27).

Every table the hub persists: identity and credentials, integration state and
versions, the tool registry, health, audit, jobs, update history and rollback
points. Autogenerated from `app.database.models`, then tidied by hand — the
JSON columns keep their `JSONB` variant so PostgreSQL gets an indexable type
while SQLite still runs the same migration.

Revision ID: 0001
Revises:
Created: 2026-08-15
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `JSONB` on PostgreSQL, plain `JSON` elsewhere. Mirrors `JsonColumn` in
# `app/database/models.py`; kept literal here because a migration must describe
# the schema as it was at this revision, not as the models describe it today.
JSON_ = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

_TZ = sa.DateTime(timezone=True)


def upgrade() -> None:
    # -- identity ----------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.String(64), nullable=False),
        sa.Column("subject", sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=True),
        sa.Column("email", sa.String(320), nullable=True),
        sa.Column("scopes", JSON_, nullable=False),
        sa.Column("is_service_account", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", _TZ, nullable=False),
        sa.Column("last_seen_at", _TZ, nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_subject", "users", ["subject"], unique=True)
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "integration_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(512), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("principal", sa.String(255), nullable=True),
        sa.Column("integration", sa.String(64), nullable=True),
        # Fernet ciphertext. Plaintext never reaches this table (arch §21).
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("created_at", _TZ, nullable=False),
        sa.Column("updated_at", _TZ, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_integration_credentials_key", "integration_credentials", ["key"], unique=True)
    op.create_index("ix_integration_credentials_name", "integration_credentials", ["name"])
    op.create_index("ix_integration_credentials_principal", "integration_credentials", ["principal"])
    op.create_index("ix_integration_credentials_integration", "integration_credentials", ["integration"])
    op.create_index("ix_credentials_principal_name", "integration_credentials", ["principal", "name"])

    # -- integrations ------------------------------------------------------
    op.create_table(
        "integrations",
        sa.Column("id", sa.String(64), nullable=False),
        sa.Column("namespace", sa.String(64), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=False),
        sa.Column("source_type", sa.String(32), nullable=False),
        sa.Column("trust", sa.String(32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("current_version_id", sa.String(128), nullable=True),
        sa.Column("last_status", sa.String(32), nullable=False),
        sa.Column("last_checked_at", _TZ, nullable=True),
        sa.Column("tool_count", sa.Integer(), nullable=False),
        sa.Column("created_at", _TZ, nullable=False),
        sa.Column("updated_at", _TZ, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_integrations_namespace", "integrations", ["namespace"], unique=True)
    op.create_index("ix_integrations_enabled", "integrations", ["enabled"])

    op.create_table(
        "integration_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("version_id", sa.String(128), nullable=False),
        sa.Column("source_type", sa.String(32), nullable=False),
        sa.Column("repository", sa.String(512), nullable=True),
        sa.Column("branch", sa.String(255), nullable=True),
        sa.Column("commit_sha", sa.String(64), nullable=True),
        sa.Column("package_version", sa.String(128), nullable=True),
        sa.Column("image_digest", sa.String(128), nullable=True),
        sa.Column("install_path", sa.String(1024), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("tool_digest", sa.String(64), nullable=True),
        sa.Column("installed_by", sa.String(255), nullable=True),
        sa.Column("installed_at", _TZ, nullable=False),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "version_id", name="uq_version_per_integration"),
    )
    op.create_index("ix_integration_versions_integration_id", "integration_versions", ["integration_id"])
    op.create_index("ix_integration_versions_version_id", "integration_versions", ["version_id"])
    op.create_index("ix_integration_versions_is_current", "integration_versions", ["is_current"])

    op.create_table(
        "tool_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("tool_name", sa.String(128), nullable=False),
        sa.Column("qualified_name", sa.String(255), nullable=False),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_schema", JSON_, nullable=False),
        sa.Column("output_schema", JSON_, nullable=True),
        sa.Column("annotations", JSON_, nullable=True),
        sa.Column("risk_level", sa.String(16), nullable=False),
        sa.Column("risk_source", sa.String(32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("discovered_at", _TZ, nullable=False),
        sa.Column("last_called_at", _TZ, nullable=True),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "tool_name", name="uq_tool_per_integration"),
    )
    op.create_index("ix_tool_registry_integration_id", "tool_registry", ["integration_id"])
    op.create_index("ix_tool_registry_qualified_name", "tool_registry", ["qualified_name"], unique=True)
    op.create_index("ix_tool_registry_risk_level", "tool_registry", ["risk_level"])
    op.create_index("ix_tool_registry_enabled", "tool_registry", ["enabled"])

    op.create_table(
        "integration_health",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("tool_count", sa.Integer(), nullable=False),
        sa.Column("protocol_version", sa.String(32), nullable=True),
        sa.Column("server_version", sa.String(128), nullable=True),
        sa.Column("checked_at", _TZ, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_integration_health_integration_id", "integration_health", ["integration_id"])
    op.create_index("ix_integration_health_checked_at", "integration_health", ["checked_at"])
    op.create_index("ix_health_integration_time", "integration_health", ["integration_id", "checked_at"])

    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("rule", JSON_, nullable=False),
        sa.Column("updated_by", sa.String(255), nullable=True),
        sa.Column("updated_at", _TZ, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_policies_integration_id", "policies", ["integration_id"], unique=True)

    # -- audit & jobs ------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", _TZ, nullable=False),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column("trace_id", sa.String(64), nullable=True),
        sa.Column("action", sa.String(48), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("user_id", sa.String(255), nullable=True),
        sa.Column("integration", sa.String(64), nullable=True),
        sa.Column("tool", sa.String(128), nullable=True),
        sa.Column("risk_level", sa.String(16), nullable=True),
        sa.Column("decision", sa.String(16), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        # Redacted metadata only — never raw tool arguments (arch §24).
        sa.Column("arguments", JSON_, nullable=True),
        sa.Column("context", JSON_, nullable=True),
        sa.Column("client_ip", sa.String(64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_timestamp", "audit_logs", ["timestamp"])
    op.create_index("ix_audit_logs_request_id", "audit_logs", ["request_id"])
    op.create_index("ix_audit_logs_trace_id", "audit_logs", ["trace_id"])
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"])
    op.create_index("ix_audit_logs_status", "audit_logs", ["status"])
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"])
    op.create_index("ix_audit_logs_integration", "audit_logs", ["integration"])
    op.create_index("ix_audit_logs_tool", "audit_logs", ["tool"])
    op.create_index("ix_audit_user_time", "audit_logs", ["user_id", "timestamp"])
    op.create_index("ix_audit_integration_time", "audit_logs", ["integration", "timestamp"])

    op.create_table(
        "update_jobs",
        sa.Column("id", sa.String(64), nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("integrations", JSON_, nullable=False),
        sa.Column("parameters", JSON_, nullable=False),
        sa.Column("result", JSON_, nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(512), nullable=True),
        sa.Column("requested_by", sa.String(255), nullable=True),
        sa.Column("request_id", sa.String(64), nullable=True),
        sa.Column("created_at", _TZ, nullable=False),
        sa.Column("started_at", _TZ, nullable=True),
        sa.Column("finished_at", _TZ, nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_update_jobs_kind", "update_jobs", ["kind"])
    op.create_index("ix_update_jobs_status", "update_jobs", ["status"])
    op.create_index("ix_update_jobs_created_at", "update_jobs", ["created_at"])

    op.create_table(
        "update_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("job_id", sa.String(64), nullable=True),
        sa.Column("from_version", sa.String(128), nullable=True),
        sa.Column("to_version", sa.String(128), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("rolled_back", sa.Boolean(), nullable=False),
        sa.Column("stage_reached", sa.String(48), nullable=True),
        sa.Column("tools_added", JSON_, nullable=False),
        sa.Column("tools_removed", JSON_, nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("started_at", _TZ, nullable=False),
        sa.Column("finished_at", _TZ, nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_update_history_integration_id", "update_history", ["integration_id"])
    op.create_index("ix_update_history_job_id", "update_history", ["job_id"])
    op.create_index("ix_update_history_succeeded", "update_history", ["succeeded"])

    op.create_table(
        "rollback_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("integration_id", sa.String(64), nullable=False),
        sa.Column("version_id", sa.String(128), nullable=False),
        sa.Column("backup_path", sa.String(1024), nullable=False),
        sa.Column("reason", sa.String(64), nullable=False),
        sa.Column("lock_entry", JSON_, nullable=True),
        sa.Column("tool_snapshot", JSON_, nullable=True),
        sa.Column("created_by", sa.String(255), nullable=True),
        sa.Column("created_at", _TZ, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rollback_points_integration_id", "rollback_points", ["integration_id"])
    op.create_index("ix_rollback_points_created_at", "rollback_points", ["created_at"])
    op.create_index("ix_rollback_integration_time", "rollback_points", ["integration_id", "created_at"])


def downgrade() -> None:
    """Drop everything, children first. Indexes go with their tables."""
    for table in (
        "rollback_points",
        "update_history",
        "update_jobs",
        "audit_logs",
        "policies",
        "integration_health",
        "tool_registry",
        "integration_versions",
        "integrations",
        "integration_credentials",
        "users",
    ):
        op.drop_table(table)
